### ISSUE TITLE
Restore support for Command History in IntelliJ 14.1

### ISSUE THREAD

**Issue by retronym** [orfjackal/idea-sbt-plugin#104]
The first release of the plugin for IDEA 14.1 (idea-sbt-plugin 1.7.0) had to revert to using a `TextConsole` for the User Interface, rather than the richer `LanguageConsole`. This was done in #10.

This was due to changes in (non-public) APIs in the IntelliJ Platform that we used to implement the UI.

Help is needed from someone familiar with the IntelliJ platform to restore this feature.

**Comment by OlegYch** [comment]
i have a mostly working fix here https://github.com/OlegYch/idea-sbt-plugin/commit/c9a88b5fe937f4de2b59b6fd9721f5d1b633bec5
the only problem currently is that if sbt tab is not visible when you're opening project, text input doesn't work, but works after you reopen the project

**Comment by refried** [comment]
Is there a Jetbrains issue we can vote on to help this move forward?  As it stands I basically am using idea-sbt-plugin to have hyperlinked compilation errors, but have to use `sbt console` at a terminal in order to use keyboard shortcuts like the Up key.  Or M-Delete and other normal line-editing shortcuts.

**Comment by alexvetter** [comment]
:+1:

**Comment by mschwerhoff** [comment]
I'd also love to see this feature re-enabled. It is a real pitty that IntelliJ still doesn't provide good native support for sbt tasks such as test-only.

**Comment by mcamou** [comment]
Any news on this one? We have issues running some of our tests from IntelliJ (such as separating unit from integration tests, testQuick, etc...) and would love to have command history in the SBT console

**Comment by OlegYch** [comment]
in idea 2016.2 command history appears to work with plugin 1.6.0 with some minor fixes (from https://github.com/OlegYch/idea-sbt-plugin)
